### ISSUE TITLE
Error in addModelSetting function when uploading modelDesign to database 

### ISSUE THREAD

**Issue by nbehzad** [OHDSI/PatientLevelPrediction#312] opened 2022-08-30 00:02 UTC
**Describe the bug**
When using the runMultiplePlp function in the develop branch with the LR, NB, and XgBoost models, all of the models are correctly generated and evaluated, and plpResult appears to be error-free. However, when inserting the XgBoost result into the database at the end of the process, I received the following error:

```sh
Error in data.frame(modelType = modelType, modelSettingsJson = json) : arguments imply differing number of rows: 0, 1

11. stop(gettextf("arguments imply differing number of rows: %s", paste(unique(nrows), collapse = ", ")), domain = NA)

10. data.frame(modelType = modelType, modelSettingsJson = json)

9. addModelSetting(conn = conn, resultSchema = databaseSchemaSettings$resultSchema, 
targetDialect = databaseSchemaSettings$targetDialect, modelType = attr(object$modelSettings$param, 
"settings")$modelType, json = object$modelSettings, tablePrefix = databaseSchemaSettings$tablePrefix, 
tempEmulationSchema = databaseSchemaSettings$tempEmulationSchema)

8. insertModelDesignSettings(object = object, conn = conn, databaseSchemaSettings = databaseSchemaSettings, 
cohortDefinitions = cohortDefinitions)

7. insertModelDesignInDatabase(object = runPlp$model$modelDesign, 
conn = conn, databaseSchemaSettings = databaseSchemaSettings, 
cohortDefinitions = cohortDefinitions)

6. addRunPlpToDatabase(runPlp = runPlp, conn = conn, databaseSchemaSettings = databaseSchemaSettings, 
cohortDefinitions = cohortDefinitions, databaseList = databaseList, 
modelSaveLocation = modelSaveLocation)

5. addMultipleRunPlpToDatabase(conn = conn, databaseSchemaSettings = createDatabaseSchemaSettings(resultSchema = "main"), 
cohortDefinitions = cohortDefinitions, databaseList = databaseList, 
resultLocation = resultLocation, modelSaveLocation = sqliteLocation)

4. insertResultsToSqlite(resultLocation = saveDirectory, cohortDefinitions = cohortDefinitions, 
databaseList = createDatabaseList(cdmDatabaseSchemas = databaseDetails$cohortDatabaseSchema), 
sqliteLocation = sqliteLocation)

3. runMultiplePlp(databaseDetails = databaseDetails, modelDesignList = getModelDesignList(config), 
onlyFetchData = F, logSettings = createLogSettings(), saveDirectory = "./PlpMultiOutput") at multiplePrediction.R#202

2. runMultiplePrediction(config, logger)

1. system.time(runMultiplePrediction(config, logger))
```

In the `insertModelDesignSettings` function (uploadToDatabaseModelDesign.R), `addModelSettings` are called with the following arguments.

```sh
 modSetId <- addModelSetting(
    conn = conn, 
    resultSchema = databaseSchemaSettings$resultSchema, 
    targetDialect = databaseSchemaSettings$targetDialect,
    modelType = attr(object$modelSettings$param, 'settings')$modelType, # make this the same as model$trainDetails$modelName?
    json = object$modelSettings, 
    tablePrefix = databaseSchemaSettings$tablePrefix,
    tempEmulationSchema = databaseSchemaSettings$tempEmulationSchema
  )
```
 I think the issue is due to the Model Type becoming NULL while it is set as `attr(object$modelSettings$param, 'settings')$modelType`. However, I am wondering why this happens only with XgBoost. Please find the log file below:

**PLP Log File**

Deleting existing tables
Creating PLP results tables
  |===============================================================================| 100%
Executing SQL took 0.0681 secs
Inserting result @ ./PlpMultiOutput/Analysis_1/plpResult into database
result loaded
Adding TAR
  |===============================================================================| 100%
Executing SQL took 0.00388 secs
tarId: 1
Adding cohorts from input list
converting json to character
Adding cohort Cohort: 1
tId: 1
Adding cohorts from input list
converting json to character
Adding cohort Cohort: 2
oId: 2
Adding new population settings
popSetId: 1
Adding new covariate settings
covSetId: 1
Adding new model settings
modSetId: 1
Adding new plp data settings
plpDataSetId: 1
Adding new feature_engineering settings
FESetId: 1
Adding new sample settings
sampleSetId: 1
Adding new tidy covariates settings
tidySetId: 1
Adding new split settings
splitId: 1
  |===============================================================================| 100%
Executing SQL took 0.00632 secs
modelDesignId: 1
  |===============================================================================| 100%
Executing SQL took 0.00367 secs
Database cdm_prolonged_opioid already exists
  |===============================================================================| 100%
Executing SQL took 0.0036 secs
modelId: 1 inserted for modelDesignId 1and databaseId 1
TAR exists
Adding cohorts from input list
converting json to character
json in jsons:TRUE
Cohort Cohort: 1 exists in result database with id1
Adding cohorts from input list
converting json to character
json in jsons:TRUE
Cohort Cohort: 2 exists in result database with id2
Population settings exists
Split setting exists
Inserting performance...
  |===============================================================================| 100%
Executing SQL took 0.00576 secs
performanceId: 1
Inserting attrition for performance 1
Adding PredictionDistribution
Inserting predictionDistribution for performance 1
Adding ThresholdSummary
Inserting thresholdSummary for performance 1
Adding EvaluationStatistics
Inserting evaluationSummary for performance 1
Adding CalibrationSummary
Inserting calibrationSummary for performance 1
Adding DemographicSummary
Inserting demographicSummary for performance 1
Restricting to covariates included in model
Inserting covariateSummary for result 1
Inserting result @ ./PlpMultiOutput/Analysis_2/plpResult into database
result loaded
TAR exists
tarId: 1
Adding cohorts from input list
converting json to character
json in jsons:TRUE
Cohort Cohort: 1 exists in result database with id1
tId: 1
Adding cohorts from input list
converting json to character
json in jsons:TRUE
Cohort Cohort: 2 exists in result database with id2
oId: 2
Population settings exists
popSetId: 1
Adding new covariate settings
covSetId: 2
Adding new model settings
modSetId: 2
Split setting exists
plpDataSetId: 1
feature engineering setting exists
FESetId: 1
sample setting exists
sampleSetId: 1
tidy covariates setting exists
tidySetId: 1
Split setting exists
splitId: 1
  |===============================================================================| 100%
Executing SQL took 0.00431 secs
modelDesignId: 2
Database cdm_prolonged_opioid already exists
Database cdm_prolonged_opioid already exists
  |===============================================================================| 100%
Executing SQL took 0.00584 secs
modelId: 2 inserted for modelDesignId 2and databaseId 1
TAR exists
Adding cohorts from input list
converting json to character
json in jsons:TRUE
Cohort Cohort: 1 exists in result database with id1
Adding cohorts from input list
converting json to character
json in jsons:TRUE
Cohort Cohort: 2 exists in result database with id2
Population settings exists
Split setting exists
Inserting performance...
  |===============================================================================| 100%
Executing SQL took 0.0059 secs
performanceId: 2
Inserting attrition for performance 2
Adding PredictionDistribution
Inserting predictionDistribution for performance 2
Adding ThresholdSummary
Inserting thresholdSummary for performance 2
Adding EvaluationStatistics
Inserting evaluationSummary for performance 2
Adding CalibrationSummary
Inserting calibrationSummary for performance 2
Adding DemographicSummary
Inserting demographicSummary for performance 2
Restricting to covariates included in model
Inserting covariateSummary for result 2
Inserting result @ ./PlpMultiOutput/Analysis_3/plpResult into database
result loaded
TAR exists
tarId: 1
Adding cohorts from input list
converting json to character
json in jsons:TRUE
Cohort Cohort: 1 exists in result database with id1
tId: 1
Adding cohorts from input list
converting json to character
json in jsons:TRUE
Cohort Cohort: 2 exists in result database with id2
oId: 2
Population settings exists
popSetId: 1
Covariate setting exists
covSetId: 1
Adding new model settings
Error in data.frame(modelType = modelType, modelSettingsJson = json) : 
  arguments imply differing number of rows: 0, 1
In addition: Warning message:
 Error in data.frame(modelType = modelType, modelSettingsJson = json) :

**Comment by jreps** [comment] 2022-08-30 01:17
I just beat you to posting about this :) see https://github.com/OHDSI/PatientLevelPrediction/issues/311 - this is caused by a bug when using ParallelLogger to save the model settings as a json.

The reason it just impacts GBM is that the bug appears to be linked to saving a list with a data.frame as the first element (Egill discovered this).  The other models must not have a list with a data.frame as the first entry.

The current way I'm thinking about bypassing this bug in ParallelLogger (not sure how long it will take the  ParallelLogger maintainers to fix) is to move the settings from being an attribute to being in the modelSettings list.  Con is that this will break backwards compatibility though, pro is it makes the settings more obvious (attributes are hidden).  I guess I could also look at adding some random thing into the modelSettings for GBM to stop the first entry being a data.frame.

**Comment by jreps** [comment] 2022-08-30 03:47
I think I fixed this in develop by changing the param slightly (it works for me now and the tests pass but I want to double check it didn't mess anything up)

**Comment by nbehzad** [comment] 2022-08-30 21:46
Thank you for providing information about this bug. This bug appears to be reported twice, but from two different perspectives. I am trying to figure out the PLP package structure by tracing the errors. According to my understanding, this bug occurs in the `addModelSetting` function in line ` data <- data.frame(modelType = modelType, modelSettingsJson = json)` and error message is related to inconsistency between data frame rows: "arguments imply differing number of rows".  After this line, the data will be saved in the database table, and it will not use ParallelLogger to save a JSON.

```sh
    ParallelLogger::logInfo('Adding new model settings')
    
    data <- data.frame(modelType = modelType,
                       modelSettingsJson = json)
    DatabaseConnector::insertTable(connection = conn, 
                                   databaseSchema = resultSchema, 
                                   tableName = paste0(tablePrefix, 'model_settings'),
                                   data = data, 
                                   dropTableIfExists = F, 
                                   createTable = F, 
                                   tempTable = F, 
                                   progressBar = T,
                                   camelCaseToSnakeCase = T,
                                   tempEmulationSchema = tempEmulationSchema)
```
Therefore, I did not understand the relationship between the ParallelLogger bug and this bug. Could you please let me know if I missed anything?

**Comment by jreps** [comment] 2022-08-30 21:58
The bug happens in runMultiplePlp() when inserting the results into an sqlite database but only because in runMultiplePlp() it loads the models before inserting. During runMultiplePlp() the models are first developed and saved per modelDesign (for example, if training 10 models based on 10 modelDesigns, then the first modelDesign is input into runPlp(), the model is fit and then saved, the next modelDeisgn is then input into runPlp(), the model is fit and then saved - this continues until all 10 models are fit),  after fitting and saving all the model in runMultiplePlp() the models are loaded iteratively and inserted into the sqlite database.  

The reason runMultiplePlp() first fits/saves all the models and then loads and inserts into the sqlite database is that my gut tells me the insertion will be more buggy and I didn't want it interfering with the main model development and saving (i.e., if something breaks the inserting into an sqlite database it won't interfere with the standard PLP model development as it happens at the end).

**Comment by nbehzad** [comment] 2022-08-31 00:20
Thanks, @jreps ! Your comments were very helpful in understanding the overall structure of the PLP package. 
I went through the codes again and noticed when the GBM model is saved `attr(plpResult$model$modelDesign$modelSettings$param, "settings")` is NULL, which I believe can be fixed by manually setting it, but I am not sure anything other than `modelType` in "settings" attribute may be used in the other functions.

**Comment by nbehzad** [comment] 2022-08-31 23:26
I just ran the `runMultiplePlp` function. This issue has been resolved. You appear to have beaten me once more in this issue :) Thanks @jreps !

**Comment by jreps** [comment] 2022-10-03 23:32
fixed in the main branch now

**Closed by jreps** 2022-10-03 23:32 UTC
Labels: fixed in develop, Caused by other OHDSI package
