### ISSUE TITLE
ParallelLogger breaks code when debugging

### ISSUE THREAD

**Issue by AniekMarkus** [OHDSI/PatientLevelPrediction#228] opened 2021-08-02 14:21 UTC
Problem with ParallelLogger when debugging in PatientLevelPrediction package. 
 
**Set up (please run in R "sessionInfo()" and copy the output here):**
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)
 
Matrix products: default
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
 
other attached packages:
 [1] shinydashboard_0.7.1          shinycssloaders_1.0.0         plotly_4.9.4.1                ggplot2_3.3.5                
 [5] shiny_1.6.0                   PatientLevelPrediction_4.3.10 FeatureExtraction_3.1.1       Andromeda_0.4.1              
 [9] dplyr_1.0.7                   DatabaseConnector_4.0.2      
 
loaded via a namespace (and not attached):
 [1] httr_1.4.2            sass_0.4.0            tidyr_1.1.3           bit64_4.0.5           jsonlite_1.7.2        viridisLite_0.4.0    
 [7] foreach_1.5.1         bslib_0.2.5.1         assertthat_0.2.1      triebeard_0.3.0       urltools_1.7.3        blob_1.2.1           
[13] yaml_2.2.1            pillar_1.6.1          RSQLite_2.2.7         lattice_0.20-41       glue_1.4.2            reticulate_1.20      
[19] digest_0.6.27         promises_1.2.0.1      colorspace_2.0-2      htmltools_0.5.1.1     httpuv_1.6.1          Matrix_1.3-2         
[25] pkgconfig_2.0.3       purrr_0.3.4           xtable_1.8-4          scales_1.1.1          later_1.2.0           ParallelLogger_2.0.2 
[31] tibble_3.1.2          generics_0.1.0        DT_0.18               ellipsis_0.3.2        cachem_1.0.5          withr_2.4.2          
[37] lazyeval_0.2.2        magrittr_2.0.1        crayon_1.4.1          mime_0.11             memoise_2.0.0         fansi_0.5.0          
[43] doParallel_1.0.16     benchmarkme_1.0.7     SqlRender_1.7.0       tools_4.0.5           data.table_1.14.0     lifecycle_1.0.0      
[49] munsell_0.5.0         zip_2.2.0             compiler_4.0.5        jquerylib_0.1.4       rlang_0.4.11          grid_4.0.5           
[55] iterators_1.0.13      rstudioapi_0.13       htmlwidgets_1.5.3     crosstalk_1.1.1       shinyWidgets_0.6.0    gtable_0.3.0         
[61] codetools_0.2-18      DBI_1.1.1             markdown_1.1          benchmarkmeData_1.0.4 R6_2.5.0              fastmap_1.1.0        
[67] bit_4.0.4             utf8_1.2.1            zeallot_0.1.0         rJava_1.0-4           parallel_4.0.5        Rcpp_1.0.6           
[73] vctrs_0.3.8           png_0.1-7             xfun_0.24             dbplyr_2.1.1          tidyselect_1.1.1     
 
**To Reproduce**
Try to run PatientLevelPrediction::runPlpAnalyses() with any target/outcome cohort/settings (verbosity = "INFO"). 
 
Add toggle breakpoint in RunPlp.R e.g. line 198 with ParallelLogger::logInfo(paste0('Patient-Level Prediction Package version ', utils::packageVersion("PatientLevelPrediction")))
 
The code breaks after this line (198) when in debug mode, the remainder of the RunPlp function is not executed.
_Error with runPlp: Error in as.vector(x, "character"): cannot coerce type 'closure' to vector of type 'character'._
 
Problem seems to be related to ParallelLogger and that it cannot write to the logger anymore, but I have not been able to create a reproducible example outside PLP package that gives the same error. ParallelLogger does not give problems when running the code without toggle breakpoint. 
 
**PLP Log File**
2021-08-02 16:05:37        [Main thread]        INFO        FeatureExtraction                Constructing features on server
2021-08-02 16:06:46        [Main thread]        INFO        FeatureExtraction                Fetching data from server
2021-08-02 16:06:47        [Main thread]        INFO        FeatureExtraction                Fetching data took 0.729 secs
2021-08-02 16:06:48        [Main thread]        INFO        PatientLevelPrediction                Outcome is 0 or 1
 
**Additional context**
I tried running PatientLevelPrediction::runPlpAnalyses() with verbosity = NONE to avoid the problem with ParallelLogger while debugging, but that causes an error even without toggle breakpoint:
_Error in if (levelToInt(level) >= levelToInt(logger$threshold)) { :
Argument is of length zero
Error during wrapup: argument is of length zero
Error: no more error handlers available (recursvie errors?); invoking 'abort' restart_

**Comment by schuemie** [comment] 2021-08-04 12:36
Intercepting warnings and errors was a bit of mess in R before version 4. It should be better in version 4, but I haven't tested the new framework thoroughly. Since you're on R v4, could you give it a try?
```r
remotes::install_github("ohdsi/ParallelLogger", ref = "globalCallingHandlers")
```

**Comment by AniekMarkus** [comment] 2021-08-09 14:20
I have tried this version of the package, it does seem to work overall but the above problem still occurs (see 'new' copy of plplog.txt below): 

2021-08-09 16:10:07	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Creating reference table
2021-08-09 16:10:07	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Writing settings csv to J:/amarkus/Documents/Experiments_EXPLORE/BenchmarkExplore/output/IPCI/OutpatientMortality_v2/settings.csv
2021-08-09 16:10:07	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Running setting 1
2021-08-09 16:10:07	[Main thread]	INFO	DatabaseConnector	connect	Connecting using PostgreSQL driver 
2021-08-09 16:10:09	[Main thread]	INFO	DatabaseConnector	executeSql	Executing SQL took 2 secs 
2021-08-09 16:10:10	[Main thread]	INFO	FeatureExtraction		Constructing features on server
2021-08-09 16:11:40	[Main thread]	INFO	DatabaseConnector	executeSql	Executing SQL took 1.5 mins 
2021-08-09 16:11:40	[Main thread]	INFO	FeatureExtraction		Fetching data from server
2021-08-09 16:11:43	[Main thread]	INFO	FeatureExtraction		Fetching data took 2.25 secs
2021-08-09 16:11:44	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Done plpData.
2021-08-09 16:11:44	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Saving data in setting 1
2021-08-09 16:11:45	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Setting population settings for setting 1
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		outcomeId: 9999
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		binary: TRUE
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		includeAllOutcomes: TRUE
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		firstExposureOnly: FALSE
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		washoutPeriod: 0
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		removeSubjectsWithPriorOutcome: TRUE
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		priorOutcomeLookback: 99999
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		requireTimeAtRisk: TRUE
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		minTimeAtRisk: 59
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		restrictTarToCohortEnd: FALSE
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		riskWindowStart: 1
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		startAnchor: cohort start
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		riskWindowEnd: 60
2021-08-09 16:11:45	[Main thread]	DEBUG	PatientLevelPrediction		endAnchor: cohort start
2021-08-09 16:11:45	[Main thread]	TRACE	PatientLevelPrediction		Removing subjects with prior outcomes (if any)
2021-08-09 16:11:45	[Main thread]	TRACE	PatientLevelPrediction		Removing non outcome subjects with insufficient time at risk (if any)
2021-08-09 16:11:45	[Main thread]	INFO	PatientLevelPrediction		Outcome is 0 or 1
2021-08-09 16:11:45	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Done pop.
2021-08-09 16:11:45	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Saving population for setting 1
2021-08-09 16:11:45	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Running runPlp for setting 1
2021-08-09 16:11:48	[Main thread]	TRACE	PatientLevelPrediction	3	Error with runPlp:Error in as.vector(x, "character"): cannot coerce type 'closure' to vector of type 'character' 
2021-08-09 16:11:48	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Done runPlp.
2021-08-09 16:11:48	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Loading data in setting 2
2021-08-09 16:11:49	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Loading population for setting2
2021-08-09 16:11:49	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Running runPlp for setting 2
2021-08-09 16:11:50	[Main thread]	TRACE	PatientLevelPrediction	3	Error with runPlp:Error in as.vector(x, "character"): cannot coerce type 'closure' to vector of type 'character' 
2021-08-09 16:11:50	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Done runPlp.
2021-08-09 16:11:50	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Loading data in setting 3
2021-08-09 16:11:50	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Loading population for setting3
2021-08-09 16:11:50	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Running runPlp for setting 3
2021-08-09 16:11:51	[Main thread]	TRACE	PatientLevelPrediction	3	Error with runPlp:Error in as.vector(x, "character"): cannot coerce type 'closure' to vector of type 'character' 
2021-08-09 16:11:51	[Main thread]	TRACE	PatientLevelPrediction	runPlpAnalyses	Done runPlp.

**Comment by jreps** [comment] 2021-08-09 14:23
This suggests an issue in runPlp -maybe a NULL value is creeping in somewhere? Can you send me the package that is failing or the json settings/skeleton id?

**Comment by jreps** [comment] 2022-10-21 14:26
Is this error still happening in PLP v6?

**Comment by egillax** [comment] 2022-10-27 15:46
I used to run into this bug as well when using the rstudio GUI to define breakpoints shortly after upgrading R to 4.0. I just tried to reproduce it on R 4.2.1 with the latest rstudio and can´t anymore, everything seems to work as it should. It only happened when putting breakpoints in functions that had parallellogger calls.

**Comment by jreps** [comment] 2022-10-27 19:53
Excellent - I will close this issue :)

**Closed by jreps** 2022-10-27 19:53 UTC
Labels: fixed in develop
