### ISSUE TITLE
Group shinkage (e.g. group lasso) during variable selection

### ISSUE THREAD

**Issue by pancodia** [OHDSI/PatientLevelPrediction#24] opened 2017-03-17 19:46 UTC
Does a prediction model with variable selection procedure (e.g. lasso regression) consider group shinkage (e.g. group lasso)? For example, if a categorical variable with C levels is converted to C-1 binary features (i.e. dummy variables), it would make more sense that all C-1 variables are kept or removed after variable selection.

**Comment by jreps** [comment] 2018-03-23 10:15
The current lasso logistic regression we use has group lasso but it is still being tested.  Hopefully it will be added this year.

**Comment by egillax** [comment] 2024-12-10 13:36
This is not in scope at the moment. And since no more people have requested this in 6.5 years I'll close this.

**Closed by egillax** 2024-12-10 13:36 UTC
